# "Enabled" must be true for the plugin to function properly
# Make sure you have your default state properly set up below before enabling!
enabled: true

# If you ever want the chunks to load new data, you must increase this
# other than that, DO NOT TOUCH THIS
chunk-version: 4

# default materials that are actually in the world
default-leaf-material: OAK_LEAVES
default-log-material: OAK_LOG
default-stripped-log-material: STRIPPED_OAK_LOG

# If a player places a leaf and it has a distance >= 7 and this setting is true,
# it will still be persistent even if world-persistence is set to false
only-follow-world-persistence-if-connected-to-log: true

use-texture-hook: false
database-type: SQLITE
use-world-whitelist: true
whitelisted-worlds:
  - "world"